# Generated by Django 5.1.5 on 2025-01-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_customuser_delete_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
